version: '3.7'
services:
  logger:
    build: .
    image: logger:1.0
    container_name: logger
    volumes:
      - ./logger_output:/logger_output
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: oCSM7dqa2nrR
    ports:
      - 5432:5432
    networks:
      - speedtest
  data_cleaner:
    build: 
      context: .
      dockerfile: DataCleaner.dockerfile
    image: data_cleaner:latest
    container_name: data_cleaner
    # environment:
    #   DB_HOST: db
    #   LOGGER_OUTPUT: /home/logger_output
    volumes:
      - ./logger_output:/home/logger_output
    depends_on:
      - db
    networks:
      - speedtest

networks:
  speedtest:
    driver: bridge
