version: '3.7'
services:
  logger:
    build: .
    image: logger:latest
    container_name: logger
    volumes:
      - ./logger_output:/logger_output
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - speedtest
  data_cleaner:
    build:
      context: .
      dockerfile: DataCleaner.dockerfile
    image: data_cleaner:latest
    container_name: data_cleaner
    environment:
      - DB_HOST=db
      - DB_PASS=${DB_PASSWORD}
      - LOGGER_OUTPUT=/home/logger_output
    volumes:
      - ./logger_output:/home/logger_output
    depends_on:
      - db
    networks:
      - speedtest
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    depends_on:
      - db
    networks:
      - speedtest

volumes:
  grafana_storage: {}

networks:
  speedtest:
    driver: bridge
